apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: mysql-pv-claim
spec: 
  accesssModes:
    - ReadWriteOnce 
  resources: 
    requests: 
      storage: 50Mi
  storageClassName: nfs-storage  
